#!/usr/bin/env bash
# Vendor the single-header vibe.h into each native package so it is
# self-contained and publishable to its ecosystem's registry (PyPI, npm,
# RubyGems, crates.io). A published package must SHIP the header — it can no
# longer rely on the repo-root libvibe.a / vibe.h being three levels up.
#
# Run this whenever vibe.h changes, then re-publish the packages.
#
#   ./vendor.sh
set -euo pipefail
cd "$(dirname "$0")"
ROOT=$(cd ../.. && pwd)
HDR="$ROOT/vibe.h"

[[ -f "$HDR" ]] || { echo "FATAL: $HDR not found"; exit 1; }

# Each native package gets vibe.h copied into a vendor/ dir, plus a tiny
# implementation TU (vibe_impl.c) so the package compiles the library from
# source instead of linking a prebuilt archive.
IMPL='/* Auto-generated by vendor.sh — do not edit.
 * Single translation unit that instantiates libvibe from the vendored header.
 * This is what makes the package self-contained: no prebuilt libvibe.a. */
#define VIBE_IMPLEMENTATION
#include "vibe.h"
'

for pkg in python node ruby rust; do
    dst="$pkg/vendor"
    mkdir -p "$dst"
    cp "$HDR" "$dst/vibe.h"
    printf '%s' "$IMPL" > "$dst/vibe_impl.c"
    echo "vendored -> $dst/{vibe.h,vibe_impl.c}"
done

echo "done. vibe.h $(grep -m1 VIBE_VERSION_STRING "$HDR" | grep -oE '"[0-9.]+"')"
