/*
 * vibe_jni.c — JNI implementation backing Vibe.java's native methods.
 *
 * Compiled to libvibejni.so, linking libvibe.a. The generated header
 * Vibe.h (from `javac -h .`) declares these Java_Vibe_* entry points.
 */
#include <jni.h>
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include "Vibe.h"   /* generated by: javac -h . Vibe.java */
#include "vibe.h"

static jstring make_string(JNIEnv *env, const char *s)
{
    return s ? (*env)->NewStringUTF(env, s) : NULL;
}

/* Fetch a UTF path; caller must release. Returns NULL on OOM. */
static const char *get_path(JNIEnv *env, jstring js)
{
    return js ? (*env)->GetStringUTFChars(env, js, NULL) : NULL;
}
static void free_path(JNIEnv *env, jstring js, const char *p)
{
    if (js && p) (*env)->ReleaseStringUTFChars(env, js, p);
}

JNIEXPORT jstring JNICALL
Java_Vibe_version(JNIEnv *env, jclass cls)
{
    return make_string(env, vibe_version());
}

JNIEXPORT jlong JNICALL
Java_Vibe_parse(JNIEnv *env, jclass cls, jstring jtext)
{
    const char *text = (*env)->GetStringUTFChars(env, jtext, NULL);
    jsize len = (*env)->GetStringUTFLength(env, jtext);

    VibeError err;
    VibeValue *root = vibe_parse(text, (size_t)len, &err);
    (*env)->ReleaseStringUTFChars(env, jtext, text);

    if (!root) {
        char msg[512];
        snprintf(msg, sizeof msg, "%s (line %d, col %d): %s",
                 vibe_error_code_string(err.code), err.line, err.column,
                 err.message ? err.message : "parse error");
        jclass exc = (*env)->FindClass(env, "Vibe$VibeException");
        if (exc) (*env)->ThrowNew(env, exc, msg);
        return 0;
    }
    return (jlong)(intptr_t)root;
}

JNIEXPORT jstring JNICALL
Java_Vibe_getString(JNIEnv *env, jclass cls, jlong handle, jstring jpath)
{
    const char *path = get_path(env, jpath);
    const char *s = vibe_get_string((VibeValue *)(intptr_t)handle, path);
    free_path(env, jpath, path);
    return make_string(env, s);
}

JNIEXPORT jlong JNICALL
Java_Vibe_getInt(JNIEnv *env, jclass cls, jlong handle, jstring jpath)
{
    const char *path = get_path(env, jpath);
    int64_t n = vibe_get_int((VibeValue *)(intptr_t)handle, path);
    free_path(env, jpath, path);
    return (jlong)n;
}

JNIEXPORT jdouble JNICALL
Java_Vibe_getFloat(JNIEnv *env, jclass cls, jlong handle, jstring jpath)
{
    const char *path = get_path(env, jpath);
    double d = vibe_get_float((VibeValue *)(intptr_t)handle, path);
    free_path(env, jpath, path);
    return (jdouble)d;
}

JNIEXPORT jboolean JNICALL
Java_Vibe_getBool(JNIEnv *env, jclass cls, jlong handle, jstring jpath)
{
    const char *path = get_path(env, jpath);
    bool b = vibe_get_bool((VibeValue *)(intptr_t)handle, path);
    free_path(env, jpath, path);
    return b ? JNI_TRUE : JNI_FALSE;
}

JNIEXPORT jint JNICALL
Java_Vibe_arraySize(JNIEnv *env, jclass cls, jlong handle, jstring jpath)
{
    const char *path = get_path(env, jpath);
    VibeArray *arr = vibe_get_array((VibeValue *)(intptr_t)handle, path);
    free_path(env, jpath, path);
    return (jint)(arr ? vibe_array_size(arr) : 0);
}

JNIEXPORT jstring JNICALL
Java_Vibe_emit(JNIEnv *env, jclass cls, jlong handle)
{
    char *s = vibe_emit((VibeValue *)(intptr_t)handle);
    jstring out = make_string(env, s);
    if (s) vibe_free(s);
    return out;
}

JNIEXPORT void JNICALL
Java_Vibe_free(JNIEnv *env, jclass cls, jlong handle)
{
    if (handle) vibe_value_free((VibeValue *)(intptr_t)handle);
}
