# VIBE Documentation Site Configuration
title: VIBE
description: Visual, Intuitive, Basic, Expressive - A human-friendly configuration language
baseurl: "/vibe"
url: "https://1ay1.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Collections
collections:
  examples:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "examples"
    values:
      layout: "example"

# Site settings
author:
  name: VIBE Team
  email: contact@vibe-lang.org

# Social
github_username: 1ay1
repository: 1ay1/vibe

# Syntax highlighting
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false

# Navigation
header_pages:
  - specification.md
  - examples.md
  - api.md
  - download.md

# Custom variables
vibe:
  version: "1.0.0"
  tagline: "Configuration language that just works"
  repo_url: "https://github.com/1ay1/vibe"
  download_url: "https://github.com/1ay1/vibe/releases"
